### ISSUE TITLE
Fiji Update Site

### ISSUE THREAD

**Issue by tischi** [cmci/MultiStackRegistration#12]
Is this plugin part of on ImageJ Update Site?
If not, I would offer to add it to EMBL-CBA update site and also contribute by maintaining it.
For example, I would change the UI to GenericDialogPlus, such that there are proper file selection UIs and the users do not have to manually copy and paste here.

**Comment by miura** [comment]
Hi @tischi  

I welcome the inclusion in the update site & a better UI. 
Maybe also ask Brad Busse, the original author, about the inclusion of the plugin in the package?

**Comment by tischi** [comment]
1. Do you know whether Brad is on github such that we could add him here?
2. How shall we do it with the repos? Do you (a) want to keep this one as a "good old ImageJ1" version and I make a new repo with all the scijava dependencies? Or, (b) should I push all changes to this repo (they would be pretty signficiant because i would make it a proper IJ2 Command)?

**Comment by ssgpers** [comment]
@tischi 
Was anything done in this respect?
Is the plugin now available at EMBL-CBA or any other update site?

**Comment by tischi** [comment]
Nope, sorry I had no time....what is your take on this? Would you like to host yourself?

**Comment by ssgpers** [comment]
I have wrote several plugins that depend on it. Would be much easier for installation by end users.
I did not establish update site yet.
Anyway, do not feel like to be the person actively supporting this plugin, but happy to contribute with testing and fixing bugs.
There 9 forks of this repo, wondering now if any of those already has an update site.

**Comment by ofrag** [comment]
Hi @miura  @tischi, 
 
Is there a way to use this plugin in the current Fiji ? 
Compile & Run does not work anymore :( 
I need to fix drift in ch1, then apply the same transformation to ch2, and run this in a macro on many files.

Thanks
Ofra

**Comment by ofrag** [comment]
Hi @miura @tischi ,

Is there a way to run this plugin in the current Fiji? 
Compile&Run does not work anymore.
I have two fluorescent channels, I need to correct the drift using one channel and then apply the same correction to the other channel. MultiStackReg works very well, but I cant automate this for multiple files , as the save/load transformation is not recordable. 

Thanks
Ofra

**Comment by DaniBodor** [comment]
I would like to raise this issue once again :)
Has anyone included this in an update site yet? It would indeed be much easier for end-users to get ahold of it in that way.

**Comment by miura** [comment]
Hi all, 

I requested to create a new update site dedicated to this plugin. 
https://forum.image.sc/t/requests-for-creating-imagej-update-sites/40051/255?u=kota

Cheers, 
Kota

**Comment by miura** [comment]
Hi all, 
now its listed in the Fiji Update Sites!
<img width="599" alt="image" src="https://user-images.githubusercontent.com/272781/168996176-4751e1b0-1555-4db4-847e-331b9f082740.png">
