### ISSUE TITLE
JAR available somewhere (update site)?

### ISSUE THREAD

**Issue by ehrenfeu** [cmci/MultiStackRegistration#2]
Hi Kota,

I'm just writing to ask if there is a JAR available from this plugin anywhere?

Cheers
Niko

**Comment by miura** [comment]
Hi @ehrenfeu 

After 4 months of incubation, here you go:

https://github.com/cmci/MultiStackRegistration/releases/tag/v1.46.0

I think in this way I can avoid dropbox sharing habit... (it's great but).
See the following thread. 

http://forum.imagej.net/t/running-multiple-instances-of-imagej/388
