### ISSUE TITLE
Question: What do the parameters mean

### ISSUE THREAD

**Issue by tischi** [cmci/MultiStackRegistration#5]
If I output the transformation matrix I get 12 numbers. Do you know what they are? 
I am asking because I would like to apply them to a 3D data-set, so I somehow have to convert the 2-D transformation to 3-D.

**Comment by tischi** [comment]
For instance, below is what I get for a translation of 30 pixels along the x-axis using the RIGID transformation. My final aim is to use the output of MultiStackReg as an input for [TransformJ>Affine].

Here are the example images: 
[translation.zip](https://github.com/cmci/MultiStackRegistration/files/343066/translation.zip)

```
MultiStackReg Transformation File
File Version 1.0
1
RIGID_BODY
Source img: 1 Target img: 1
229.99999999901203  199.999927890365
229.99999999932055  99.999927890365
229.99999999870352  299.999927890365

200.0   200.0
200.0   100.0
200.0   300.0
```

**Comment by tischi** [comment]
Below the output for "aligning" two identical images:

```
MultiStackReg Transformation File
File Version 1.0
1
RIGID_BODY
Source img: 1 Target img: 1
200.00000000000003  200.0000000000006
200.00000000000017  100.00000000000058
199.9999999999999   300.00000000000057

200.0   200.0
200.0   100.0
200.0   300.0
```

**Comment by tischi** [comment]
This is how 30 pixel translation along x would look like in TransformJ.

```
1   0   0   30
0   1   0   0
0   0   1   0
```

**Comment by tischi** [comment]
Here is the code where it actually writes the numbers:
https://github.com/cmci/MultiStackRegistration/blob/master/src/main/java/de/embl/cmci/registration/MultiStackReg_.java#L869
It is **not** the transformation matrix, but something else.

**Comment by miura** [comment]
Hi @tischi , 

The text output for transformation are three point coordinates each for reference and the target images. They are not the transformation matrix, but three corresponding points for generating a transformation matrix.
