### ISSUE TITLE
fails when using "translation"

### ISSUE THREAD

**Issue by tischi** [cmci/MultiStackRegistration#6]
aligning those two using "Translation" gives the wrong result
[translation.zip](https://github.com/cmci/MultiStackRegistration/files/343224/translation.zip)

**Comment by miura** [comment]
Please test with the latest release, I think translation and affine transformation were mixed up causing the bug in the previous release. 

https://github.com/cmci/MultiStackRegistration/releases/tag/v1.46.1

I will wait for your test results.

**Comment by miura** [comment]
Hi @tischi 

can I close this?

**Comment by tischi** [comment]
I had no time to look at it, because i am teaching in a course the whole
week.

---

_Dr. Christian Tischer_
Advanced Light Microscopy Facility
EMBL Heidelberg
Meyerhofstr.1
D - 69117 Heidelberg
Phone +49(0)6221 387-8951
www.embl.de/almf

**Comment by tischi** [comment]
I checked it and it works now!
