### ISSUE TITLE
Maven dependency  with JitPack

### ISSUE THREAD

**Issue by ssgpers** [cmci/MultiStackRegistration#8]
Hi Kota,

I try to import MultiStackRegistration to my project as maven dependency.

    <dependency>
      <groupId>com.github.cmci</groupId>
      <artifactId>MultiStackRegistration_</artifactId>
      <version>1.46.2</version>
      <scope>compile</scope>
    </dependency>

But the following error always occurs during compilation:
[ERROR] Failed to execute goal on project AutoMicTools_: Could not resolve dependencies for project xxx_:jar:1.1.1-SNAPSHOT: Failed to collect dependencies at com.github.cmci:MultiStackRegistration_:jar:1.46.2: Failed to read artifact descriptor for com.github.cmci:MultiStackRegistration_:jar:1.46.2: Could not transfer artifact com.github.cmci:MultiStackRegistration_:pom:1.46.2 from/to jitpack.io (https://jitpack.io): Access denied to https://jitpack.io/com/github/cmci/MultiStackRegistration_/1.46.2/MultiStackRegistration_-1.46.2.pom. Error code 401, Repo not found or no access token provided -> [Help 1]
[ERROR] 

I think the problem is thet artifactID and repository name are slightly different (by "_").
Is there any way around to have correct maven import?
Thanks!

**Comment by miura** [comment]
Did you try without the underscore, like

	<dependency>
	    <groupId>com.github.cmci</groupId>
	    <artifactId>MultiStackRegistration</artifactId>
	    <version>v1.46.2</version>
	</dependency>

artifactId should be repo name not the maven artifactId in case you are using jitpack.

**Comment by ssgpers** [comment]
Thanks! Now it works.

I also tried artifactID without underscore before, But the problem was that I used "1.46.2" as a version (your version id in pom.xml file). Apparently it only works with release tag "v1.46.2".
