### ISSUE TITLE
Transformation matrix file path as an argument

### ISSUE THREAD

**Issue by danustc** [cmci/MultiStackRegistration#9]
Hi Developers, 

Is it possible to set the transformation matrix file path as an argument of the plugin instead of asking the user to enter it in the middle of execution? I am asking this because I would like to execute MultiStackReg in a macro, save the .txt output with a given file name, then close the images: 

**run("MultiStackReg", "stack_1="+ title_ref+" action_1=[Use as Reference] file_1=[] stack_2 ="+ title_align + " action_2=[Align to First Stack] file_2=[] transformation=Affine save");**

I tried to specify the output file name by using "save=<file path>" but it does not work. I think in the current version save is a boolean variable and the file name is not included in the initial arguments of the function. This makes batch processing not quite convenient.

**Comment by facepalm** [comment]
In your example, put it in file_2 instead.  

If the plugin's run in a context that would use a file (either a load action or an alignment with the save option), it'll look at the file_* parameters and try to open it there.  Only if it's empty or fails to open does it prompt the user for the file.

If you've got macro recorder running while doing it manually, it should note the syntax of the complete call.
